rtkwlf/ui

.github/workflows/deploy.yml
package-lock.json
package.json

[AWN-32688] Test publish

---

.github/workflows/deploy.yml
src/components/accordion/Accordion.tsx
src/components/accordion/AccordionItem.tsx
src/components/accordion/__tests__/Accordion.spec.tsx
src/components/accordion/context.ts
src/components/accordion/stories/Accordion.mdx
src/components/accordion/stories/Accordion.stories.tsx
src/components/accordion/types.ts

- Adding accordion component as an orchestration of collapse components
- Unit Testing Implemented

[AWN-32688] Accordion Component

---

.npmignore
package-lock.json
package.json

I mistakenly forgot to exclude the docs from from the bundle which is increasing its size by quite a bit.

Exclude docs folder from bundle

---

.github/workflows/main.yml
src/hooks/index.ts
src/index.ts
src/utils/getRelativePosition.spec.ts
src/utils/getRelativePosition.stories.mdx
src/utils/getRelativePosition.ts
src/utils/index.ts

- Adding relative positioner helper. Main objective with this utility is to take two elements and position one with respect to another. It will take into account scroll position and relative positioning. Will be used for tooltips, selects, etc for positioning.

Relative Positioner

---

src/components/accordion/Accordion.tsx
src/components/accordion/AccordionItem.tsx
src/components/accordion/__tests__/Accordion.spec.tsx
src/components/accordion/context.ts
src/components/accordion/stories/Accordion.mdx
src/components/accordion/stories/Accordion.stories.tsx
src/components/accordion/types.ts
src/components/collapse/Collapse.tsx
src/components/collapse/Content.tsx
src/components/collapse/Header.tsx
src/components/collapse/__tests__/Collapse.spec.tsx
src/components/collapse/stories/Collapse.mdx
src/components/collapse/stories/Collapse.stories.tsx

- Changed `active` to `expanded`
- Added `focus-within` and `hover` styles to collapse for better UX when filling out forms in an accordion/collapse.

Accordion Updates

---

.storybook/preview-head.html
src/components/accordion/__tests__/Accordion.spec.tsx
src/components/button/StyledButton.tsx
src/components/button/__tests__/Button.spec.tsx
src/components/collapse/__tests__/Collapse.spec.tsx
src/components/floater/__tests__/Floater.spec.tsx
src/components/index.ts
src/components/input/Suffix.tsx
src/components/input/__tests__/Input.spec.tsx
src/components/modal/Content.tsx
src/components/modal/Footer.tsx
src/components/modal/Header.tsx
src/components/modal/Modal.tsx
src/components/modal/StyledModal.tsx
src/components/modal/__tests__/Modal.spec.tsx
src/components/modal/stories/Modal.mdx
src/components/modal/stories/Modal.stories.tsx
src/components/panel/Panel.tsx
src/components/panel/__tests__/Panel.spec.tsx
src/components/portal/__tests__/Portal.spec.tsx
src/theme/colors.ts
src/theme/index.ts
src/theme/types.ts

- Adding Modal Component
- Fixing up styles for Button to match new figma designs
- Fixed imports
- Exported Component Props in Bundle

Modal Component

---

.storybook/components/ThemeDecorator.tsx
src/components/input/Input.tsx
src/components/modal/Content.tsx
src/components/modal/Footer.tsx
src/components/modal/Header.tsx
src/components/modal/Modal.tsx
src/components/modal/StyledModal.tsx

- Fixes the Modal having no styles when a ThemeProvider isnt used.

Fixing Modal To Account for No Theme Provider

---

src/components/panel/Panel.tsx
src/theme/index.ts
src/theme/types.ts

- Adding padding and margin to the Panel component

Panel Padding and Margin

---

src/components/input/Input.tsx
src/components/input/StyledInput.tsx
src/components/input/stories/Input.stories.tsx

- Adds a danger colored '*' to the beginning of any label

Adding required label to input

---

src/components/modal/Modal.tsx
src/docs/theme.stories.mdx
src/hooks/useTheme.ts
src/index.ts
src/styled/index.ts

- Fixes the modal drag out
- Removes uneeded exports

Modal Drag Out Fix

---

.storybook/addons.js
.storybook/config.js
.storybook/presets.js
package-lock.json
package.json
src/components/divider/Divider.tsx
src/components/divider/StyledDivider.tsx
src/components/divider/__tests__/Divider.spec.tsx
src/components/divider/stories/Divider.mdx
src/components/divider/stories/Divider.stories.tsx
src/index.ts
src/theme/index.ts
src/theme/types.ts

A divider is a line used to group content on lists and layouts

New reusable component - Divider

---

src/components/typography/Label.tsx
src/components/typography/Typography.tsx
src/components/typography/__tests__/Typography.spec.tsx
src/components/typography/stories/Typography.mdx
src/components/typography/stories/Typography.stories.tsx
src/index.ts
src/theme/colors.ts
src/theme/index.ts
src/theme/types.ts

Label Typography Component and Documentation Updates

---

src/components/button/Button.tsx
src/components/button/StyledButton.tsx
src/components/button/stories/Button.stories.tsx
src/theme/colors.ts
src/theme/index.ts
src/theme/types.ts

- Adding support for secondary and tertiary buttons

Secondary and Tertiary buttons

---

package-lock.json
package.json
src/components/panel/Panel.tsx
src/theme/index.ts

- Panel box-shadow
- Updating styled-components

Panel Fixes

---

src/components/layout/Content.tsx
src/components/layout/Footer.tsx
src/components/layout/Header.tsx
src/components/layout/Layout.tsx
src/components/layout/Sider.tsx
src/components/layout/__tests__/Layout.spec.tsx
src/components/layout/stories/Layout.mdx
src/components/layout/stories/Layout.stories.tsx
src/index.ts
src/theme/index.ts
src/theme/types.ts

- Adding Sider Component support to layout

Layout Sider Component

---

src/components/accordion/AccordionItem.tsx
src/components/accordion/stories/Accordion.stories.tsx
src/components/collapse/Collapse.tsx
src/components/collapse/Header.tsx
src/components/collapse/__tests__/Collapse.spec.tsx
src/components/collapse/stories/Collapse.mdx
src/components/collapse/stories/Collapse.stories.tsx

- Provides ability to disable a collapsed item
- Extends to AccordionItem

Adding disabled prop to Collapse

---

package-lock.json
package.json
plopfile.js
src/components/divider/__tests__/Divider.spec.tsx
templates/Component.mdx.hbs
templates/Component.spec.tsx.hbs
templates/Component.stories.tsx.hbs
templates/Component.tsx.hbs

- Adding support for generating new components using plop
- `npm run gen` will prompt you to enter a name for a new component and will generate all of the necassary files for creating a new component.

Adding Support for Generating new Components

---

.github/workflows/main.yml
.gitignore
package-lock.json
package.json
setupTest.js
src/components/input/Input.tsx
src/components/input/StyledInput.tsx
src/components/input/__tests__/Input.spec.tsx
src/components/input/stories/Input.mdx
src/components/input/stories/Input.stories.tsx
src/theme/index.ts
src/theme/types.ts

Enable the `<Input/>` component to display as a multi-line text area

Add textarea to the input field

---

.github/workflows/deploy.yml
package-lock.json
package.json

Adding NODE_AUTH_TOKEN to workflows config

---

.github/workflows/deploy.yml

Adding the explicit registry to npmrc for workflows

---

src/components/icons/Loading.tsx
src/components/table/Body.tsx
src/components/table/Table.tsx
src/components/table/TableLoading.tsx
src/components/table/__tests__/Table.spec.tsx
src/components/table/stories/Table.mdx
src/components/table/stories/Table.stories.tsx

- Adding support for loading state in the table.
- Useful for when users want to asynchronously load data

Table loading state

---

src/components/tabs/Tabs.tsx
src/components/tabs/TabsItem.tsx
src/components/tabs/stories/Tabs.stories.tsx
src/components/typography/Body.tsx
src/theme/colors.ts
src/theme/types.ts

- Modifies the look of the tabs
- Removes ink bar flickering when the component first renders

Tabs Style Change

---

src/components/tabs/TabsItem.tsx
src/theme/index.ts

- Adds an opacity filter to the tab items to make it more obvious which tabs are selected.

Making Selected Tab More Prominent

---

src/components/tooltip/stories/Tooltip.stories.tsx

- Makes the tooltip go clockwise

Tooltip Demo Change

---

src/components/menu/Menu.tsx
src/components/menu/MenuContext.ts
src/components/menu/MenuItem.tsx
src/components/menu/__tests__/Menu.spec.tsx
src/components/tooltip/stories/Tooltip.stories.tsx

- Allows the defaultSelectedItem to be set

Adding defaultSelectedItem prop to Menu

---

package-lock.json
package.json
src/components/menu/Menu.tsx

Set the selected menu item even when the onClick isnt defined

0.1.7 Bump

---

src/components/input/StyledInput.tsx
src/theme/index.ts
src/theme/types.ts

- Noticed in nucleus that the font is different. I wanted the ability to use the new fonts in the input instead of inheriting.

Adding the ability to change the font family on the input

---

package-lock.json
package.json
src/index.ts

- export `FormItem` to make it available

Export FormItem

---

package-lock.json
package.json
src/components/button/StyledButton.tsx
src/components/formItem/FormItem.tsx
src/components/formItem/stories/FormItem.stories.tsx

- Fixes an issue with the ghost button when focused in a loading state in chrome
- Added Label to FormItem label

Chrome Fix for Ghost Button in Loading state and FormItem Label

---

src/components/icons/Loading.tsx
src/components/input/stories/Input.mdx
src/components/toggle/Toggle.tsx
src/components/toggle/ToggleIcon.tsx
src/components/toggle/__tests__/Toggle.spec.tsx
src/components/toggle/stories/Toggle.mdx
src/components/toggle/stories/Toggle.stories.tsx
src/docs/theme.stories.mdx
src/theme/index.ts
src/theme/types.ts
templates/Component.mdx.hbs
templates/Component.tsx.hbs

[WIP] Toggle Component

---

package-lock.json
package.json
src/components/dropPad/DropPad.tsx
src/components/dropPad/DropPadFile.tsx
src/components/dropPad/__tests__/DropPad.spec.tsx
src/components/dropPad/stories/DropPad.mdx
src/components/dropPad/stories/DropPad.stories.tsx
src/components/formItem/FormItem.tsx
src/components/icons/File.tsx
src/components/icons/PaperClip.tsx
src/components/icons/TrashAlt.tsx
src/components/icons/index.ts
src/components/radio/RadioItem.tsx
src/theme/colors.ts
src/theme/index.ts
src/theme/types.ts

- Includes initial DropPad component which will allow users to select files to be uploaded. I want to see how it works in a project.
Things left to finish in the future: 
- manage the unique keys of each file to allow `onDelete` and `percentUploaded` to work as expected.

Initial DropPad Component

---

.storybook/components/ThemeDecorator.tsx
src/components/panel/Panel.tsx
src/components/panel/__tests__/Panel.spec.tsx
src/components/panel/stories/Panel.mdx
src/components/panel/stories/Panel.stories.tsx
src/theme/index.ts
src/theme/types.ts

- Adds ability to have Title in panel.

Title on Panel

---

src/components/dropPad/DropPad.tsx
src/components/dropPad/DropPadFile.tsx
src/components/dropPad/stories/DropPad.stories.tsx

- adds the progress bar to the droppad file component

Adding progress bar to droppad file

---

package-lock.json
package.json
src/components/dropPad/DropPad.tsx
src/components/dropPad/DropPadFile.tsx
src/components/dropPad/__tests__/DropPad.spec.tsx
src/components/dropPad/stories/DropPad.mdx
src/components/dropPad/stories/DropPad.stories.tsx
src/hooks/hooks.stories.mdx
src/hooks/index.ts
src/hooks/useUploadOnMountEffect.spec.ts
src/hooks/useUploadOnMountEffect.ts
src/index.ts

- Updates the DropPad component to be `display what data you give me` kind of component
- Created a `useUploadOnMountEffect` to provide the ability to upload a file that has been dropped on the `DropPad`

useUploadOnMountEffect and DropPad Updates

---

.huskyrc.json
src/components/select/Select.tsx

Porting some of Tom's useful helper functions for dealing with react-select options from portalreact into the ui kit.

Add helper types/functions for using Select widget

---

package-lock.json
package.json
src/components/markdown/Markdown.tsx
src/components/markdown/__tests__/Markdown.spec.tsx
src/components/markdown/stories/Markdown.mdx
src/components/markdown/stories/Markdown.stories.tsx
src/index.ts

Add markdown component

---

package-lock.json
package.json
src/components/markdown/Markdown.tsx
src/components/typography/Body.tsx
src/components/typography/Title.tsx
src/index.ts
src/theme/colors.ts
src/theme/types.ts

- Applies styles to the text in the markdown component.

Style the Text in the Markdown Component

---

.github/workflows/deploy.yml

- Adds auto tag and merge for deploy

Auto Version and Tag for deploy

---

.github/workflows/deploy.yml

- Enables auto deploy on merge to master branch

Enabling Auto-Deploy
